language: android
android:
  components:
    - build-tools-28.0.3
    - android-28
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

install:
  - echo y | sdkmanager "ndk-bundle"
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source $HOME/.cargo/env
  - rustup target add armv7-linux-androideabi   # for arm
  - rustup target add i686-linux-android        # for x86
  - rustup target add aarch64-linux-android     # for arm64
  - rustup target add x86_64-linux-android      # for x86_64

script: ./gradlew build
